//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MAP1                        157
#define IDB_PLAYER                      158
#define IDB_BITMAP3                     161
#define IDB_HERO1                       161
#define IDB_HERO_R                      161
#define IDB_BITMAP4                     164
#define IDB_MAP1_1                      164
#define IDB_SCARECROW                   166
#define IDB_BITMAP5                     167
#define IDB_ATTACK1                     167
#define IDB_BLOODALMOSTDIE              168
#define IDB_BLOODFULL                   169
#define IDB_BLOODLITTLEDAMAGED          170
#define IDB_BLOOD2OF4                   171
#define IDB_BLOOD1OF4                   172
#define IDB_BITMAP11                    173
#define IDB_BLOOD3OF4                   173
#define IDB_COUNTER1                    174
#define IDB_COUNTER2                    175
#define IDB_COUNTER3                    176
#define IDB_COUNTER4                    177
#define IDB_COUNTER5                    178
#define IDB_COUNTER6                    179
#define IDB_COUNTER7                    180
#define IDB_COUNTER8                    181
#define IDB_CLOCK1                      183
#define IDB_CLOCK2                      184
#define IDB_CLOCK3                      185
#define IDB_CLOCK4                      186
#define IDB_CLOCK5                      187
#define IDB_BITMAP12                    188
#define IDB_CLOCK6                      188
#define IDB_CLOCK7                      189
#define IDB_CLOCK8                      190
#define IDB_HERO_L                      191
#define IDB_WALKINGL1                   192
#define IDB_WALKINGL2                   193
#define IDB_WALKINGL3                   194
#define IDB_WALKINGL4                   195
#define IDB_WALKINGR1                   196
#define IDB_WALKINGR2                   197
#define IDB_WALKINGR3                   198
#define IDB_WALKINGR4                   199
#define IDB_FIREATTACK                  200
#define IDB_BITMAP6                     202
#define IDB_BEGGERSWORD                 202
#define IDB_MAP1_2                      204
#define IDB_BITMAP8                     205
#define IDB_MAP1_6                      205
#define IDB_STARTBACKGROUND             211
#define IDB_BLOOD2OVER10                212
#define IDB_BLOOD3OVER10                213
#define IDB_BLOOD4OVER10                214
#define IDB_BLOOD6OVER10                215
#define IDB_BLOOD7OVER10                216
#define IDB_BLOOD8OVER10                217
#define IDB_STATUSBAR                   218
#define IDB_SKILLEPIC                   219
#define IDB_BITMAP9                     220
#define IDB_SKILLQFIREPIC               220
#define IDB_ITEMHEALTH                  222
#define IDB_ATTRIBUTEFIRE               223
#define IDB_ATTRIBUTEICE                224
#define IDB_ATTRIBUTEPLANT              225
#define IDB_ATTACKPLANT                 226
#define IDB_SKILLQPLANTPIC              227
#define IDB_BITMAP7                     228
#define IDB_SKILLQICEPIC                228
#define IDB_ITEMPOTION                  230
#define IDB_ITEMCLOCK                   231
#define IDB_BITMAP10                    232
#define IDB_BOX                         232
#define IDB_START1                      234
#define IDB_START2                      235
#define IDB_STORY1                      236
#define IDB_BITMAP16                    237
#define IDB_STORY2                      237
#define IDB_BOXDAMAGED                  238
#define IDB_ITEMRANDOMATTRIBUTE         240
#define IDB_MAP2_1                      241
#define IDB_MAP2_2                      243
#define IDB_MAP2_3                      244
#define IDB_BITMAP13                    245
#define IDB_MAP2_4                      245
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
